#hybrid
#create table hybrid(column1 string,column2 string,column3 string,column4 string,column5 string,column6 string,column7 string,column8 string,column9 string,column10 string,measure1 int,measure2 int,measure3 int,measure4 int) STORED BY 'org.apache.carbondata.format' tblproperties ("COLUMN_GROUPS"="(column2,column3,column4),(column7,column8,column9)")
#LOAD DATA LOCAL INPATH 'D:\\github\\FeatureTest\\input\\10dim_4msr.csv' INTO table hybrid options('FILEHEADER'='column1,column2,column3,column4,column5,column6,column7,column8,column9,column10,measure1,measure2,measure3,measure4')
#select * from hybrid where column3='column311' and column7='column74'
#
#select column4 from hybrid
#select column1,column4 from hybrid
#select column2,column4,column5,column6 from hybrid
#select column7,column10 from hybrid where column10='column101'
#select column6,column7 from hybrid
#
#create table hybrid(column1 string,column2 string,column3 string,column4 string,column5 string,column6 string,column7 string,column8 string,column9 string,column10 string,measure1 int,measure2 int,measure3 int,measure4 int) STORED BY 'org.apache.carbondata.format' tblproperties ("COLUMN_GROUPS"="(column2,column3,column4),(column7,column8,column9))")
#LOAD DATA LOCAL INPATH 'D:\\github\\FeatureTest\\input\\10dim_4msr.csv' INTO table hybrid options('FILEHEADER'='column1,column2,column3,column4,column5,column6,column7,column8,column9,column10,measure1,measure2,measure3,measure4')
#
#
#normal
#create table normal(column1 string,column2 string,column3 string,column4 string,column5 string,column6 string,column7 string,column8 string,column9 string,column10 string,measure1 int,measure2 int,measure3 int,measure4 int) STORED BY 'org.apache.carbondata.format'
#LOAD DATA LOCAL INPATH 'D:\\github\\FeatureTest\\input\\10dim_4msr.csv' INTO table normal options('FILEHEADER'='column1,column2,column3,column4,column5,column6,column7,column8,column9,column10,measure1,measure2,measure3,measure4')
#select column1,count(*) from normal group by column1 having count(*)>4
#
#create table normal_hive(column1 string,column2 string,column3 string,column4 string,column5 string,column6 string,column7 string,column8 string,column9 string,column10 string,measure1 int,measure2 int,measure3 int,measure4 int)
#LOAD DATA LOCAL INPATH 'D:\\github\\FeatureTest\\input\\10dim_4msr.csv' INTO table normal_hive
#select column1,count(*) from normal_hive group by column1 having count(*)>1
#
#
#high cardinality
#drop table if exists t3
CREATE TABLE t3(ID Int, date Timestamp, country String,name String, phonetype String, serialname String, salary Int) STORED BY 'org.apache.carbondata.format' TBLPROPERTIES('DICTIONARY_EXCLUDE'='country,phonetype,serialname','DICTIONARY_INCLUDE'='ID')
#LOAD DATA LOCAL INPATH 'D:\\github\\FeatureTest\\input\\emptyDimensionData.csv' into table t3
#select ID from t3
#create table complexcarbontable(deviceInformationId int, channelsId string,ROMSize string, purchasedate string, mobile struct<imei:string, imsi:string>,MAC array<string>, locationinfo array<struct<ActiveAreaId:int, ActiveCountry:string, ActiveProvince:string, Activecity:string, ActiveDistrict:string, ActiveStreet:string>>,proddate struct<productionDate:string,activeDeactivedate:array<string>>, gamePointId double,contractNumber double) STORED BY 'org.apache.carbondata.format' TBLPROPERTIES ('DICTIONARY_INCLUDE'='deviceInformationId', 'DICTIONARY_EXCLUDE'='ROMSize,purchasedate')
#LOAD DATA local inpath 'D:\\github\\FeatureTest\\input\\complexdata.csv' INTO table complexcarbontable OPTIONS('DELIMITER'=',', 'QUOTECHAR'='\"', 'FILEHEADER'='deviceInformationId,channelsId,ROMSize,purchasedate,mobile,MAC,locationinfo,proddate,gamePointId,contractNumber','COMPLEX_DELIMITER_LEVEL_1'='$', 'COMPLEX_DELIMITER_LEVEL_2'=':')
#Join queries
#
#hive
#drop table if exists employee_hive
#create table employee_hive (empid string,empname string,mobilename string,mobilecolor string,salary int)
#LOAD DATA LOCAL INPATH 'D:/github/FeatureTest/input/join/employee.csv' INTO table employee_hive
#create table mobile_hive (mobileId string,mobileName string, mobileColor string, sales int) tblproperties('skip.header.line.count'='1')
#LOAD DATA LOCAL INPATH 'D:/github/FeatureTest/input/join/employee.csv' into table employee_hive
#LOAD DATA LOCAL INPATH 'D:/github/FeatureTest/input/join/mobile.csv' overwrite into table mobile_hive options('FILEHEADER'='mobileid,mobilename,mobilecolor,sales')
#select employee_hive.empname,mobile_hive.mobilename from employee_hive,mobile_hive where employee_hive.mobilename = mobile_hive.mobilename
#
#carbon
#
#drop table if exists employee
#drop table mobile
#drop table employee
create table if not exists employee (empid string,empname string,mobileName string,mobileColor string,salary int) stored by 'org.apache.carbondata.format'
#create table mobile (mobileId string,mobileName string, mobileColor string, sales int) stored by 'org.apache.carbondata.format'
LOAD DATA INPATH 'D:/github/FeatureTest/input/join/employee.csv' into table employee options('FILEHEADER'='empid,empname,mobilename,mobilecolor,salary')
#LOAD DATA LOCAL INPATH 'D:/github/FeatureTest/input/join/mobile.csv' into table mobile options('FILEHEADER'='mobileid,mobilename,mobilecolor,sales')
#select count(*) from employee
#select * from mobile
#select employee.empname,mobile.mobilename from employee,mobile where employee.mobilename = mobile.mobilename
#
#
#Column group measure issue
#create table hybrid(column1 string,column2 string,column3 string,column4 string,column5 string,column6 string,column7 string,column8 string,column9 string,column10 string,measure1 int,measure2 int,measure3 int,measure4 int) STORED BY 'org.apache.carbondata.format' tblproperties ("COLUMN_GROUPS"="(column2,column4,column3),(column4,column6,column5))")
#LOAD DATA LOCAL INPATH 'D:\\github\\FeatureTest\\input\\10dim_4msr.csv' INTO table hybrid options('FILEHEADER'='column1,column2,column3,column4,column5,column6,column7,column8,column9,column10,measure1,measure2,measure3,measure4')
#create table complexcarbontable(deviceInformationId int, channelsId string,ROMSize string, purchasedate string, mobile struct<imei:string, imsi:string>,MAC array<string>, locationinfo array<struct<ActiveAreaId:int, ActiveCountry:string, ActiveProvince:string, Activecity:string, ActiveDistrict:string, ActiveStreet:string>>,proddate struct<productionDate:string,activeDeactivedate:array<string>>, gamePointId double,contractNumber double) STORED BY 'org.apache.carbondata.format' TBLPROPERTIES ('DICTIONARY_INCLUDE'='deviceInformationId','COLUMN_GROUPS'='(channelsid,romsize),(mobile.imei,mobile.imsi)','DICTIONARY_EXCLUDE'='purchasedate')
#
#drop table if exists times
#create table times (empid string,empname string,mobileName timestamp,mobileColor string,salary int) stored by 'org.apache.carbondata.format' tblproperties('COLUMN_GROUPS'='(empid,empname),(mobilename,mobilecolor)')	
#CREATE TABLE IF NOT EXISTS aColumngrp4 (CUST_ID String,CUST_COUNTRY String,CUST_STATE String,CUST_CITY String,ACTIVE_AREA_ID String,ACTIVE_COUNTRY String,ACTIVE_PROVINCE String,ACTIVE_CITY String,ACTIVE_DISTRICT String,LATEST_AREAID String,LATEST_COUNTRY String,LATEST_PROVINCE String,OL_RET_DATE String,CUST_DEP_COUNT int,CUST_VEHICLE_COUNT int,CUST_ADDRESS_CNT int,CUST_CRNT_CDEMO_CNT int,CUST_CRNT_HDEMO_CNT int,CUST_CRNT_ADDR_DM int,CUST_FIRST_SHIPTO_CNT int,CUST_FIRST_SALES_CNT int,CUST_GMT_OFFSET int,CUST_DEMO_CNT int,CUST_INCOME int) STORED BY 'org.apache.carbondata.format' TBLPROPERTIES('COLUMN_GROUPS'='(cust_first_sales_cnt,cust_gmt_offset,cust_demo_cnt)')
#CREATE TABLE IF NOT EXISTS MColumngrp2 (CUST_ID String,CUST_COUNTRY String,CUST_STATE String,CUST_CITY String,ACTIVE_AREA_ID String,ACTIVE_COUNTRY String,ACTIVE_PROVINCE String,ACTIVE_CITY String,ACTIVE_DISTRICT String,LATEST_AREAID String,LATEST_COUNTRY String,LATEST_PROVINCE String,OL_RET_DATE String,CUST_DEP_COUNT int,CUST_VEHICLE_COUNT int,CUST_ADDRESS_CNT int,CUST_CRNT_CDEMO_CNT int,CUST_CRNT_HDEMO_CNT int,CUST_CRNT_ADDR_DM int,CUST_FIRST_SHIPTO_CNT int,CUST_FIRST_SALES_CNT int,CUST_GMT_OFFSET int,CUST_DEMO_CNT int,CUST_INCOME int) STORED BY 'org.apache.carbondata.format' TBLPROPERTIES('COLUMN_GROUPS'='(cust_country,cust_state),(cust_state,cust_city,active_area_id)')
#CREATE TABLE IF NOT EXISTS Columngrp28 (CUST_ID STRING,CUST_COUNTRY array<string>,CUST_STATE STRING,CUST_CITY String,ACTIVE_AREA_ID String,ACTIVE_COUNTRY String,ACTIVE_PROVINCE String,ACTIVE_CITY String,ACTIVE_DISTRICT String,LATEST_AREAID String,LATEST_COUNTRY String,LATEST_PROVINCE String,OL_RET_DATE timestamp,CUST_DEP_COUNT int,CUST_VEHICLE_COUNT int,CUST_ADDRESS_CNT int,CUST_CRNT_CDEMO_CNT int,CUST_CRNT_HDEMO_CNT int,CUST_CRNT_ADDR_DM int,CUST_FIRST_SHIPTO_CNT int,CUST_FIRST_SALES_CNT int,CUST_GMT_OFFSET int,CUST_DEMO_CNT int,CUST_INCOME int) STORED BY 'org.apache.carbondata.format' TBLPROPERTIES('COLUMN_GROUPS'='(cust_country,cust_state,cust_city)')
#CREATE TABLE IF NOT EXISTS Columngrpwithdic (CUST_ID String,CUST_COUNTRY String,CUST_STATE String,CUST_CITY String,ACTIVE_AREA_ID String,ACTIVE_COUNTRY String,ACTIVE_PROVINCE String,ACTIVE_CITY String,ACTIVE_DISTRICT String,LATEST_AREAID String,LATEST_COUNTRY String,LATEST_PROVINCE String,OL_RET_DATE String,CUST_DEP_COUNT int,CUST_VEHICLE_COUNT int,CUST_ADDRESS_CNT int,CUST_CRNT_CDEMO_CNT int,CUST_CRNT_HDEMO_CNT int,CUST_CRNT_ADDR_DM int,CUST_FIRST_SHIPTO_CNT int,CUST_FIRST_SALES_CNT int,CUST_GMT_OFFSET int,CUST_DEMO_CNT int,CUST_INCOME int) STORED BY 'org.apache.carbondata.format' TBLPROPERTIES('COLUMN_GROUPS'='( cust_country , cust_state , cust_city )')
#CREATE TABLE IF NOT EXISTS Columngrp16 (CUST_ID String,CUST_COUNTRY String,CUST_STATE String,CUST_CITY String,ACTIVE_AREA_ID String,ACTIVE_COUNTRY String,ACTIVE_PROVINCE String,ACTIVE_CITY String,ACTIVE_DISTRICT String,LATEST_AREAID String,LATEST_COUNTRY String,LATEST_PROVINCE String,OL_RET_DATE timestamp,CUST_DEP_COUNT int,CUST_VEHICLE_COUNT int,CUST_ADDRESS_CNT int,CUST_CRNT_CDEMO_CNT int,CUST_CRNT_HDEMO_CNT int,CUST_CRNT_ADDR_DM int,CUST_FIRST_SHIPTO_CNT int,CUST_FIRST_SALES_CNT int,CUST_GMT_OFFSET int,CUST_DEMO_CNT int,CUST_INCOME int) STORED BY 'org.apache.carbondata.format' TBLPROPERTIES('COLUMN_GROUPS'='(cust_country,cust_state,cust_city,ol_ret_date)')
#drop table if exists employee
#create table employee(empname string,salary bigint) STORED BY 'org.apache.carbondata.format'
#LOAD DATA LOCAL INPATH 'D:\\github\\FeatureTest\\input\\single.csv' INTO table employee
#select percentile(salary,0.1) as a from employee
#select distinct empname from employee
#drop table if exists hybrid
#drop table hybrid
#create table hybrid(column1 string,column2 timestamp,column3 string,column4 string,column5 string,column6 string,column7 string,column8 string,column9 string,column10 string,measure1 double,measure2 int,measure3 bigint) STORED BY 'org.apache.carbondata.format' tblproperties ('dictionary_include'='column2,measure1,measure2,measure3',"COLUMN_GROUPS"="(column4,column5,column3),(measure1,measure2,measure3)")
#LOAD DATA LOCAL INPATH 'D:\\github\\FeatureTest\\input\\10dim_4msr_1.csv' INTO table hybrid options('FILEHEADER'='column1,column2,column3,column4,column5,column6,column7,column8,column9,column10,measure1,measure2,measure3,measure4')
#select * from hybrid
#select count(column1) from hybrid
#select count(column2) from hybrid
#CREATE TABLE IF NOT EXISTS carbonTable (ID Int, date Timestamp, country String, name String, phonetype String, serialname String, salary bigint)STORED BY 'org.apache.carbondata.format'
#create table if not exists hiveTable(ID Int, date Timestamp, country String, name String, phonetype String, serialname String, salary bigint)row format delimited fields terminated by ','
#LOAD DATA LOCAL INPATH 'D:\github\carbondata\integration\spark\src\test\resources\bigIntDataWithHeader.csv' into table carbonTable
#LOAD DATA local inpath 'D:\github\carbondata\integration\spark\src\test\resources\bigIntDataWithoutHeader.csv' INTO table hiveTable
#select salary from carbonTable order by salary
#drop table Carbon_automation_test
#create table Carbon_automation_test (imei string,deviceInformationId int,MAC string,deviceColor string,device_backColor string,modelId string,marketName string,AMSize string,ROMSize string,CUPAudit string,CPIClocked string,series string,productionDate timestamp,bomCode string,internalModels string, deliveryTime string, channelsId string, channelsName string , deliveryAreaId string, deliveryCountry string, deliveryProvince string, deliveryCity string,deliveryDistrict string, deliveryStreet string, oxSingleNumber string, ActiveCheckTime string, ActiveAreaId string, ActiveCountry string, ActiveProvince string, Activecity string, ActiveDistrict string, ActiveStreet string, ActiveOperatorId string, Active_releaseId string, Active_EMUIVersion string, Active_operaSysVersion string, Active_BacVerNumber string, Active_BacFlashVer string, Active_webUIVersion string, Active_webUITypeCarrVer string,Active_webTypeDataVerNumber string, Active_operatorsVersion string, Active_phonePADPartitionedVersions string, Latest_YEAR int, Latest_MONTH int, Latest_DAY int, Latest_HOUR string, Latest_areaId string, Latest_country string, Latest_province string, Latest_city string, Latest_district string, Latest_street string, Latest_releaseId string, Latest_EMUIVersion string, Latest_operaSysVersion string, Latest_BacVerNumber string, Latest_BacFlashVer string, Latest_webUIVersion string, Latest_webUITypeCarrVer string, Latest_webTypeDataVerNumber string, Latest_operatorsVersion string, Latest_phonePADPartitionedVersions string, Latest_operatorId string, gamePointDescription string, gamePointId int,contractNumber int) STORED BY 'org.apache.carbondata.format' TBLPROPERTIES('DICTIONARY_EXCLUDE'='Latest_MONTH,Latest_DAY,deviceInformationId')
#LOAD DATA LOCAL INPATH 'D:\github\carbondata\integration\spark\src\test\resources\100_olap.csv' INTO table Carbon_automation_test options('DELIMITER'= ',' ,'QUOTECHAR'= '"', 'FILEHEADER'= 'imei,deviceInformationId,MAC,deviceColor,device_backColor,modelId,marketName,AMSize,ROMSize,CUPAudit,CPIClocked,series,productionDate,bomCode,internalModels,deliveryTime,channelsId,channelsName,deliveryAreaId,deliveryCountry,deliveryProvince,deliveryCity,deliveryDistrict,deliveryStreet,oxSingleNumber,contractNumber,ActiveCheckTime,ActiveAreaId,ActiveCountry,ActiveProvince,Activecity,ActiveDistrict,ActiveStreet,ActiveOperatorId,Active_releaseId,Active_EMUIVersion,Active_operaSysVersion,Active_BacVerNumber,Active_BacFlashVer,Active_webUIVersion,Active_webUITypeCarrVer,Active_webTypeDataVerNumber,Active_operatorsVersion,Active_phonePADPartitionedVersions,Latest_YEAR,Latest_MONTH,Latest_DAY,Latest_HOUR,Latest_areaId,Latest_country,Latest_province,Latest_city,Latest_district,Latest_street,Latest_releaseId,Latest_EMUIVersion,Latest_operaSysVersion,Latest_BacVerNumber,Latest_BacFlashVer,Latest_webUIVersion,Latest_webUITypeCarrVer,Latest_webTypeDataVerNumber,Latest_operatorsVersion,Latest_phonePADPartitionedVersions,Latest_operatorId,gamePointId,gamePointDescription')
#SELECT AMSize, ActiveAreaId, SUM(gamePointId) AS Sum_gamePointId FROM (select * from Carbon_automation_test) SUB_QRY GROUP BY AMSize, ActiveAreaId ORDER BY AMSize ASC, ActiveAreaId ASC
#
#drop table if exists Carbon_automation_test_hive
#create table Carbon_automation_test_hive (imei string,deviceInformationId int,MAC string,deviceColor string,device_backColor string,modelId string,marketName string,AMSize string,ROMSize string,CUPAudit string,CPIClocked string,series string,productionDate timestamp,bomCode string,internalModels string, deliveryTime string, channelsId string, channelsName string , deliveryAreaId string, deliveryCountry string, deliveryProvince string, deliveryCity string,deliveryDistrict string, deliveryStreet string, oxSingleNumber string, ActiveCheckTime string, ActiveAreaId string, ActiveCountry string, ActiveProvince string, Activecity string, ActiveDistrict string, ActiveStreet string, ActiveOperatorId string, Active_releaseId string, Active_EMUIVersion string, Active_operaSysVersion string, Active_BacVerNumber string, Active_BacFlashVer string, Active_webUIVersion string, Active_webUITypeCarrVer string,Active_webTypeDataVerNumber string, Active_operatorsVersion string, Active_phonePADPartitionedVersions string, Latest_YEAR int, Latest_MONTH int, Latest_DAY int, Latest_HOUR string, Latest_areaId string, Latest_country string, Latest_province string, Latest_city string, Latest_district string, Latest_street string, Latest_releaseId string, Latest_EMUIVersion string, Latest_operaSysVersion string, Latest_BacVerNumber string, Latest_BacFlashVer string, Latest_webUIVersion string, Latest_webUITypeCarrVer string, Latest_webTypeDataVerNumber string, Latest_operatorsVersion string, Latest_phonePADPartitionedVersions string, Latest_operatorId string, gamePointDescription string, gamePointId int,contractNumber int)row format delimited fields terminated by ','
#LOAD DATA LOCAL INPATH 'D:\github\carbondata\integration\spark\src\test\resources\100_olap.csv' INTO table Carbon_automation_test_hive
#SELECT AMSize, ActiveAreaId, SUM(gamePointId) AS Sum_gamePointId FROM (select * from Carbon_automation_test_hive) SUB_QRY GROUP BY AMSize, ActiveAreaId ORDER BY AMSize ASC, ActiveAreaId ASC
#SELECT ActiveAreaId FROM Carbon_automation_test_hive
create table colgrp_disorder1 (column1 string,column2 string,column3 string,column4 string,column5 string,column6 string,column7 string,column8 string,column9 string,column10 string,measure1 int,measure2 int,measure3 int,measure4 int) STORED BY 'org.apache.carbondata.format' TBLPROPERTIES ('COLUMN_GROUPS'='(column7,column8,column9),(column2,column3,column4)')
create table colgrp_disorder2 (column1 string,column2 string,column3 string,column4 string,column5 string,column6 string,column7 string,column8 string,column9 string,column10 string,measure1 int,measure2 int,measure3 int,measure4 int) STORED BY 'org.apache.carbondata.format' TBLPROPERTIES ('COLUMN_GROUPS'='(column7),(column2,column3,column4)')
create table colgrp_disorder3 (column1 string,column2 string,column3 string,column4 string,column5 string,column6 string,column7 string,column8 string,column9 string,column10 string,measure1 int,measure2 int,measure3 int,measure4 int) STORED BY 'org.apache.carbondata.format' TBLPROPERTIES ('COLUMN_GROUPS'='(column7)')
#create table hybrid(column1 string,column2 string,column3 string,column4 string,column5 string,column6 string,column7 string,column8 string,column9 string,column10 string,measure1 int,measure2 int,measure3 int,measure4 int) STORED BY 'org.apache.carbondata.format' tblproperties ("COLUMN_GROUPS"="(column2,column3,column4),(column7,column8,column9))")
#LOAD DATA LOCAL INPATH 'D:\\github\\FeatureTest\\input\\10dim_4msr.csv' INTO table hybrid options('FILEHEADER'='column1,column2,column3,column4,column5,column6,column7,column8,column9,column10,measure1,measure2,measure3,measure4')
#select * from hybrid
#create table cg(col1 string, col2 string,msr1 int) stored by 'org.apache.carbondata.format' tblproperties('dictionary_include'='msr1','column_groups'='(col1,col2)')
#drop table Carbon_automation_test
#create table Carbon_automation_test (imei string,deviceInformationId int,MAC string,deviceColor string,device_backColor string,modelId string,marketName string,AMSize string,ROMSize string,CUPAudit string,CPIClocked string,series string,productionDate timestamp,bomCode string,internalModels string, deliveryTime string, channelsId string, channelsName string , deliveryAreaId string, deliveryCountry string, deliveryProvince string, deliveryCity string,deliveryDistrict string, deliveryStreet string, oxSingleNumber string, ActiveCheckTime string, ActiveAreaId string, ActiveCountry string, ActiveProvince string, Activecity string, ActiveDistrict string, ActiveStreet string, ActiveOperatorId string, Active_releaseId string, Active_EMUIVersion string, Active_operaSysVersion string, Active_BacVerNumber string, Active_BacFlashVer string, Active_webUIVersion string, Active_webUITypeCarrVer string,Active_webTypeDataVerNumber string, Active_operatorsVersion string, Active_phonePADPartitionedVersions string, Latest_YEAR int, Latest_MONTH int, Latest_DAY int, Latest_HOUR string, Latest_areaId string, Latest_country string, Latest_province string, Latest_city string, Latest_district string, Latest_street string, Latest_releaseId string, Latest_EMUIVersion string, Latest_operaSysVersion string, Latest_BacVerNumber string, Latest_BacFlashVer string, Latest_webUIVersion string, Latest_webUITypeCarrVer string, Latest_webTypeDataVerNumber string, Latest_operatorsVersion string, Latest_phonePADPartitionedVersions string, Latest_operatorId string, gamePointDescription string, gamePointId int,contractNumber int) STORED BY 'org.apache.carbondata.format' TBLPROPERTIES('DICTIONARY_EXCLUDE'='Latest_MONTH,Latest_DAY,deviceInformationId')
#LOAD DATA LOCAL INPATH 'D:/github/carbondata/integration/spark/src/test/resources/100_olap.csv' INTO table Carbon_automation_test options('DELIMITER'= ',' ,'QUOTECHAR'= '\"', 'FILEHEADER'= 'imei,deviceInformationId,MAC,deviceColor,device_backColor,modelId,marketName,AMSize,ROMSize,CUPAudit,CPIClocked,series,productionDate,bomCode,internalModels,deliveryTime,channelsId,channelsName,deliveryAreaId,deliveryCountry,deliveryProvince,deliveryCity,deliveryDistrict,deliveryStreet,oxSingleNumber,contractNumber,ActiveCheckTime,ActiveAreaId,ActiveCountry,ActiveProvince,Activecity,ActiveDistrict,ActiveStreet,ActiveOperatorId,Active_releaseId,Active_EMUIVersion,Active_operaSysVersion,Active_BacVerNumber,Active_BacFlashVer,Active_webUIVersion,Active_webUITypeCarrVer,Active_webTypeDataVerNumber,Active_operatorsVersion,Active_phonePADPartitionedVersions,Latest_YEAR,Latest_MONTH,Latest_DAY,Latest_HOUR,Latest_areaId,Latest_country,Latest_province,Latest_city,Latest_district,Latest_street,Latest_releaseId,Latest_EMUIVersion,Latest_operaSysVersion,Latest_BacVerNumber,Latest_BacFlashVer,Latest_webUIVersion,Latest_webUITypeCarrVer,Latest_webTypeDataVerNumber,Latest_operatorsVersion,Latest_phonePADPartitionedVersions,Latest_operatorId,gamePointId,gamePointDescription')
#select  imei from Carbon_automation_test where contractNumber is NOT null
#drop table integer_table_03
#CREATE TABLE integer_table_03(imei string,age int) STORED BY 'org.apache.carbondata.format'
#LOAD DATA INPATH 'D:/github/carbondata/integration/spark/src/test/resources/datawithmaxinteger.csv' INTO table integer_table_03 options ('DELIMITER'=',','QUOTECHAR'='"')
#select age from integer_table_03 where age is not null
#drop table if exists msr
#create table msr(country string,state int,gdp double) stored by 'org.apache.carbondata.format'
#load data local inpath 'D:\github\FeatureTest\input\country_growth.csv' into table msr
#select * from msr
#drop table if exists employee
#drop table if exists mobile
#create table employee (empid string,empname string,mobilename string,mobilecolor string,salary int) stored by 'org.apache.carbondata.format'
#create table mobile (mobileid string,mobilename string, mobilecolor string, sales int) stored by 'org.apache.carbondata.format'
#LOAD DATA LOCAL INPATH 'D:\github\FeatureTest\input\join\employee.csv' into table employee options('FILEHEADER'='empid,empname,mobilename,mobilecolor,salary')
#LOAD DATA LOCAL INPATH 'D:\github\FeatureTest\input\join\mobile.csv' into table mobile options('FILEHEADER'='mobileid,mobilename,mobilecolor,sales')
#select employee.empname,mobile.mobilename from employee,mobile where employee.mobilename = mobile.mobilename
#CREATE TABLE double2short (name String, value double) STORED BY 'org.apache.carbondata.format'
#LOAD data local inpath 'D:\github\FeatureTest\input\eason.csv' into table double2short options('fileheader'='name,value')
#select * from double2short
#drop table if exists double2byte
#create table double2byte (name String, value double) stored by 'org.apache.carbondata.format'
#load data local inpath 'D:\github\FeatureTest\input\double2byte.csv' into table double2byte options('fileheader'='name,value')
#select * from double2byte
#drop table if exists Carbon_automation_test
#create table Carbon_automation_test (imei string,deviceInformationId int,MAC string,deviceColor string,device_backColor string,modelId string,marketName string,AMSize string,ROMSize string,CUPAudit string,CPIClocked string,series string,productionDate timestamp,bomCode string,internalModels string, deliveryTime string, channelsId string, channelsName string , deliveryAreaId string, deliveryCountry string, deliveryProvince string, deliveryCity string,deliveryDistrict string, deliveryStreet string, oxSingleNumber string, ActiveCheckTime string, ActiveAreaId string, ActiveCountry string, ActiveProvince string, Activecity string, ActiveDistrict string, ActiveStreet string, ActiveOperatorId string, Active_releaseId string, Active_EMUIVersion string, Active_operaSysVersion string, Active_BacVerNumber string, Active_BacFlashVer string, Active_webUIVersion string, Active_webUITypeCarrVer string,Active_webTypeDataVerNumber string, Active_operatorsVersion string, Active_phonePADPartitionedVersions string, Latest_YEAR int, Latest_MONTH int, Latest_DAY int, Latest_HOUR string, Latest_areaId string, Latest_country string, Latest_province string, Latest_city string, Latest_district string, Latest_street string, Latest_releaseId string, Latest_EMUIVersion string, Latest_operaSysVersion string, Latest_BacVerNumber string, Latest_BacFlashVer string, Latest_webUIVersion string, Latest_webUITypeCarrVer string, Latest_webTypeDataVerNumber string, Latest_operatorsVersion string, Latest_phonePADPartitionedVersions string, Latest_operatorId string, gamePointDescription string, gamePointId int,contractNumber int) STORED BY 'org.apache.carbondata.format' TBLPROPERTIES('DICTIONARY_EXCLUDE'='Latest_MONTH,Latest_DAY,deviceInformationId')
#LOAD DATA LOCAL INPATH 'D:\github\carbondata\integration\spark\src\test\resources\100_olap.csv' INTO table Carbon_automation_test options('DELIMITER'= ',' ,'QUOTECHAR'= '"', 'FILEHEADER'= 'imei,deviceInformationId,MAC,deviceColor,device_backColor,modelId,marketName,AMSize,ROMSize,CUPAudit,CPIClocked,series,productionDate,bomCode,internalModels,deliveryTime,channelsId,channelsName,deliveryAreaId,deliveryCountry,deliveryProvince,deliveryCity,deliveryDistrict,deliveryStreet,oxSingleNumber,contractNumber,ActiveCheckTime,ActiveAreaId,ActiveCountry,ActiveProvince,Activecity,ActiveDistrict,ActiveStreet,ActiveOperatorId,Active_releaseId,Active_EMUIVersion,Active_operaSysVersion,Active_BacVerNumber,Active_BacFlashVer,Active_webUIVersion,Active_webUITypeCarrVer,Active_webTypeDataVerNumber,Active_operatorsVersion,Active_phonePADPartitionedVersions,Latest_YEAR,Latest_MONTH,Latest_DAY,Latest_HOUR,Latest_areaId,Latest_country,Latest_province,Latest_city,Latest_district,Latest_street,Latest_releaseId,Latest_EMUIVersion,Latest_operaSysVersion,Latest_BacVerNumber,Latest_BacFlashVer,Latest_webUIVersion,Latest_webUITypeCarrVer,Latest_webTypeDataVerNumber,Latest_operatorsVersion,Latest_phonePADPartitionedVersions,Latest_operatorId,gamePointId,gamePointDescription')
#select imei, Latest_DAY from Carbon_automation_test where imei IS NOT NULL
#select * from Carbon_automation_test where AMSize >= ''
#
#
#drop table if exists employee
#drop table if exists mobile
#create table employee (empid string,empname string,mobilename string,mobilecolor string,salary int) stored by 'org.apache.carbondata.format'
#create table mobile (mobileid string,mobilename string, mobilecolor string, sales int) stored by 'org.apache.carbondata.format'
#LOAD DATA LOCAL INPATH 'D:/github/incubator-carbondata/integration/spark/src/test/resources/join/employee.csv' into table employee options('FILEHEADER'='empid,empname,mobilename,mobilecolor,salary')
#LOAD DATA LOCAL INPATH 'D:/github/incubator-carbondata/integration/spark/src/test/resources/join/mobile.csv' into table mobile options('FILEHEADER'='mobileid,mobilename,mobilecolor,sales')
#select employee.empname,mobile.mobilename from employee,mobile where employee.mobilename = mobile.mobilename or employee.mobilecolor=mobile.mobilecolor
#
#
#drop table if exists alldatatypestableAGG
#CREATE TABLE alldatatypestableAGG (empno int, empname String, designation String, doj Timestamp, workgroupcategory int, workgroupcategoryname String, deptno int, deptname String, projectcode int, projectjoindate Timestamp, projectenddate Timestamp,attendance int,utilization int,salary int) STORED BY 'org.apache.carbondata.format'
#LOAD DATA LOCAL INPATH 'D:/github/incubator-carbondata/integration/spark/src/test/resources/data.csv' INTO TABLE alldatatypestableAGG OPTIONS('DELIMITER'= ',', 'QUOTECHAR'= '"')
#select empno,empname,utilization,count(salary),sum(empno) from alldatatypestableAGG where empname in ('arvind','ayushi') group by empno,empname,utilization
#drop table if exists alldatatypescubeAGG_hive
#CREATE TABLE alldatatypescubeAGG_hive (empno int, empname String, designation String, doj Timestamp, workgroupcategory int, workgroupcategoryname String, deptno int, deptname String, projectcode int, projectjoindate Timestamp, projectenddate Timestamp,attendance int,utilization int,salary int)row format delimited fields terminated by ','
#LOAD DATA LOCAL INPATH 'D:/github/incubator-carbondata/integration/spark/src/test/resources/datawithoutheader.csv' INTO TABLE alldatatypescubeAGG_hive
#explain extended select empno,empname,utilization,count(salary),sum(empno) from alldatatypescubeAGG_hive where empname in ('arvind','ayushi') group by empno,empname,utilization
#drop table if exists directDictionaryTable
#CREATE TABLE if not exists directDictionaryTable (empno int,doj Timestamp,salary int) STORED BY 'org.apache.carbondata.format'
#LOAD DATA local inpath 'D:/github/incubator-carbondata/integration/spark/src/test/resources/datasample.csv' INTO TABLE directDictionaryTable OPTIONS('DELIMITER'= ',', 'QUOTECHAR'= '"')
#select doj from directDictionaryTable where regexp_replace(doj, '-', '/') NOT IN ('2016/03/14 15:00:09')
#create table complex_filter(test1 int, test2 array<String>,test3 array<bigint>,test4 array<int>,test5 array<decimal>,test6 array<timestamp>,test7 array<double>) STORED BY 'org.apache.carbondata.format'
#LOAD DATA INPATH 'D:/github/incubator-carbondata/integration/spark/src/test/resources/array1.csv'  INTO TABLE complex_filter options ('DELIMITER'=',', 'QUOTECHAR'='"', 'COMPLEX_DELIMITER_LEVEL_1'='$', 'FILEHEADER'= 'test1,test2,test3,test4,test5,test6,test7')
#select test5 from complex_filter
#
#drop table if exists double_nater_table
#create table double_nater_table(name string, value double) stored by 'org.apache.carbondata.format'
#load data inpath 'D:\github\FeatureTest\input\test_nater.csv' into table double_nater_table options('delimiter'=',','fileheader'='name,value')
#select * from double_nater_table
#
#
#drop table if exists state
#create table state(state string, capital string, district_count int) stored by 'org.apache.carbondata.format'
#load data local inpath 'D:\github\FeatureTest\input\state.csv' into table state options('fileheader'='state,capital,district_count')
#load data local inpath 'D:\github\FeatureTest\input\state.csv' into table state options('fileheader'='state,capital,district_count')
#load data local inpath 'D:\github\FeatureTest\input\state.csv' into table state options('fileheader'='state,capital,district_count')
#load data local inpath 'D:\github\FeatureTest\input\state.csv' into table state options('fileheader'='state,capital,district_count')
#select count(*) from state
#alter table state compact 'major'
#select capital from state where in(capital)=false
#select t.x["abcc"] from (select str_to_map(capital) x from state) t where t.x["abcc"] is null
#CREATE table testtable (empno string, empname String, designation String, doj String,workgroupcategory string, workgroupcategoryname String, deptno string, deptname String,projectcode string, projectjoindate String, projectenddate String,attendance double,utilization double,salary double) STORED BY 'org.apache.carbondata.format' TBLPROPERTIES('DICTIONARY_EXCLUDE'='empno,empname,designation,doj,workgroupcategory,workgroupcategoryname,deptno,deptname,projectcode,projectjoindate,projectenddate')
#create table testhivetable(empno string, empname String, designation string, doj String,workgroupcategory string, workgroupcategoryname String,deptno string, deptname String,projectcode string, projectjoindate String,projectenddate String, attendance double,utilization double,salary double)row format delimited fields terminated by ','
#LOAD DATA local inpath 'D:/github/incubator-carbondata/integration/spark/src/test/resources/data.csv' INTO table testtable
#LOAD DATA local inpath 'D:/github/incubator-carbondata/integration/spark/src/test/resources/datawithoutheader.csv' overwrite INTO table testhivetable
#select * from testtable
#select * from testhivetable
#drop table if exists ut
#create table ut(name string,utilization double) stored by 'org.apache.carbondata.format'
#load data inpath 'D:\github\FeatureTest\input\ut.csv' into table ut options('fileheader'='name,utilization')
#select * from ut
#create table bigint2byte(name string,val bigint) stored by 'org.apache.carbondata.format'
#load data inpath 'D:\github\FeatureTest\input\compression\bigint2byte.csv' into table bigint2byte options('fileheader'='name,val')
#
#
#
#
#drop table if exists THive
#create table THive (imei string,deviceInformationId int,MAC string,deviceColor string,device_backColor string,modelId string,marketName string,AMSize string,ROMSize string,CUPAudit string,CPIClocked string,series string,productionDate timestamp,bomCode string,internalModels string, deliveryTime string, channelsId string, channelsName string , deliveryAreaId string, deliveryCountry string, deliveryProvince string, deliveryCity string,deliveryDistrict string, deliveryStreet string, oxSingleNumber string, ActiveCheckTime string, ActiveAreaId string, ActiveCountry string, ActiveProvince string, Activecity string, ActiveDistrict string, ActiveStreet string, ActiveOperatorId string, Active_releaseId string, Active_EMUIVersion string, Active_operaSysVersion string, Active_BacVerNumber string, Active_BacFlashVer string, Active_webUIVersion string, Active_webUITypeCarrVer string,Active_webTypeDataVerNumber string, Active_operatorsVersion string, Active_phonePADPartitionedVersions string, Latest_YEAR int, Latest_MONTH int, Latest_DAY Decimal(30,10), Latest_HOUR string, Latest_areaId string, Latest_country string, Latest_province string, Latest_city string, Latest_district string, Latest_street string, Latest_releaseId string, Latest_EMUIVersion string, Latest_operaSysVersion string, Latest_BacVerNumber string, Latest_BacFlashVer string, Latest_webUIVersion string, Latest_webUITypeCarrVer string, Latest_webTypeDataVerNumber string, Latest_operatorsVersion string, Latest_phonePADPartitionedVersions string, Latest_operatorId string, gamePointDescription string,gamePointId double,contractNumber BigInt) ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
#LOAD DATA local INPATH 'D:\github\incubator-carbondata\integration\spark\src\test\resources\100_olap.csv' INTO TABLE THive
#drop table if exists TCarbon
#create table TCarbon (imei string,deviceInformationId int,MAC string,deviceColor string,device_backColor string,modelId string,marketName string,AMSize string,ROMSize string,CUPAudit string,CPIClocked string,series string,productionDate timestamp,bomCode string,internalModels string, deliveryTime string, channelsId string, channelsName string , deliveryAreaId string, deliveryCountry string, deliveryProvince string, deliveryCity string,deliveryDistrict string, deliveryStreet string, oxSingleNumber string, ActiveCheckTime string, ActiveAreaId string, ActiveCountry string, ActiveProvince string, Activecity string, ActiveDistrict string, ActiveStreet string, ActiveOperatorId string, Active_releaseId string, Active_EMUIVersion string, Active_operaSysVersion string, Active_BacVerNumber string, Active_BacFlashVer string, Active_webUIVersion string, Active_webUITypeCarrVer string,Active_webTypeDataVerNumber string, Active_operatorsVersion string, Active_phonePADPartitionedVersions string, Latest_YEAR int, Latest_MONTH int, Latest_DAY Decimal(30,10), Latest_HOUR string, Latest_areaId string, Latest_country string, Latest_province string, Latest_city string, Latest_district string, Latest_street string, Latest_releaseId string, Latest_EMUIVersion string, Latest_operaSysVersion string, Latest_BacVerNumber string, Latest_BacFlashVer string, Latest_webUIVersion string, Latest_webUITypeCarrVer string, Latest_webTypeDataVerNumber string, Latest_operatorsVersion string, Latest_phonePADPartitionedVersions string, Latest_operatorId string, gamePointDescription string,gamePointId double,contractNumber BigInt) STORED BY 'org.apache.carbondata.format'
#insert into TCarbon select * from THive
#select imei,deviceInformationId,MAC,deviceColor,device_backColor,modelId,marketName,AMSize,ROMSize,CUPAudit,CPIClocked,series,productionDate,bomCode,internalModels,deliveryTime,channelsId,channelsName,deliveryAreaId,deliveryCountry,deliveryProvince,deliveryCity,deliveryDistrict,deliveryStreet,oxSingleNumber,contractNumber,ActiveCheckTime,ActiveAreaId,ActiveCountry,ActiveProvince,Activecity,ActiveDistrict,ActiveStreet,ActiveOperatorId,Active_releaseId,Active_EMUIVersion,Active_operaSysVersion,Active_BacVerNumber,Active_BacFlashVer,Active_webUIVersion,Active_webUITypeCarrVer,Active_webTypeDataVerNumber,Active_operatorsVersion,Active_phonePADPartitionedVersions,Latest_YEAR,Latest_MONTH,Latest_DAY,Latest_HOUR,Latest_areaId,Latest_country,Latest_province,Latest_city,Latest_district,Latest_street,Latest_releaseId,Latest_EMUIVersion,Latest_operaSysVersion,Latest_BacVerNumber,Latest_BacFlashVer,Latest_webUIVersion,Latest_webUITypeCarrVer,Latest_webTypeDataVerNumber,Latest_operatorsVersion,Latest_phonePADPartitionedVersions,Latest_operatorId,gamePointId,gamePointDescription from THive order by imei,deviceInformationId,MAC,deviceColor,device_backColor,modelId,marketName,AMSize,ROMSize,CUPAudit,CPIClocked,series,productionDate,bomCode,internalModels,deliveryTime,channelsId,channelsName,deliveryAreaId,deliveryCountry,deliveryProvince,deliveryCity,deliveryDistrict,deliveryStreet,oxSingleNumber,contractNumber,ActiveCheckTime,ActiveAreaId,ActiveCountry,ActiveProvince,Activecity,ActiveDistrict,ActiveStreet,ActiveOperatorId,Active_releaseId,Active_EMUIVersion,Active_operaSysVersion,Active_BacVerNumber,Active_BacFlashVer,Active_webUIVersion,Active_webUITypeCarrVer,Active_webTypeDataVerNumber,Active_operatorsVersion,Active_phonePADPartitionedVersions,Latest_YEAR,Latest_MONTH,Latest_DAY,Latest_HOUR,Latest_areaId,Latest_country,Latest_province,Latest_city,Latest_district,Latest_street,Latest_releaseId,Latest_EMUIVersion,Latest_operaSysVersion,Latest_BacVerNumber,Latest_BacFlashVer,Latest_webUIVersion,Latest_webUITypeCarrVer,Latest_webTypeDataVerNumber,Latest_operatorsVersion,Latest_phonePADPartitionedVersions,Latest_operatorId,gamePointId,gamePointDescription
#select imei,deviceInformationId,MAC,deviceColor,device_backColor,modelId,marketName,AMSize,ROMSize,CUPAudit,CPIClocked,series,productionDate,bomCode,internalModels,deliveryTime,channelsId,channelsName,deliveryAreaId,deliveryCountry,deliveryProvince,deliveryCity,deliveryDistrict,deliveryStreet,oxSingleNumber,contractNumber,ActiveCheckTime,ActiveAreaId,ActiveCountry,ActiveProvince,Activecity,ActiveDistrict,ActiveStreet,ActiveOperatorId,Active_releaseId,Active_EMUIVersion,Active_operaSysVersion,Active_BacVerNumber,Active_BacFlashVer,Active_webUIVersion,Active_webUITypeCarrVer,Active_webTypeDataVerNumber,Active_operatorsVersion,Active_phonePADPartitionedVersions,Latest_YEAR,Latest_MONTH,Latest_DAY,Latest_HOUR,Latest_areaId,Latest_country,Latest_province,Latest_city,Latest_district,Latest_street,Latest_releaseId,Latest_EMUIVersion,Latest_operaSysVersion,Latest_BacVerNumber,Latest_BacFlashVer,Latest_webUIVersion,Latest_webUITypeCarrVer,Latest_webTypeDataVerNumber,Latest_operatorsVersion,Latest_phonePADPartitionedVersions,Latest_operatorId,gamePointId,gamePointDescription from TCarbon order by imei,deviceInformationId,MAC,deviceColor,device_backColor,modelId,marketName,AMSize,ROMSize,CUPAudit,CPIClocked,series,productionDate,bomCode,internalModels,deliveryTime,channelsId,channelsName,deliveryAreaId,deliveryCountry,deliveryProvince,deliveryCity,deliveryDistrict,deliveryStreet,oxSingleNumber,contractNumber,ActiveCheckTime,ActiveAreaId,ActiveCountry,ActiveProvince,Activecity,ActiveDistrict,ActiveStreet,ActiveOperatorId,Active_releaseId,Active_EMUIVersion,Active_operaSysVersion,Active_BacVerNumber,Active_BacFlashVer,Active_webUIVersion,Active_webUITypeCarrVer,Active_webTypeDataVerNumber,Active_operatorsVersion,Active_phonePADPartitionedVersions,Latest_YEAR,Latest_MONTH,Latest_DAY,Latest_HOUR,Latest_areaId,Latest_country,Latest_province,Latest_city,Latest_district,Latest_street,Latest_releaseId,Latest_EMUIVersion,Latest_operaSysVersion,Latest_BacVerNumber,Latest_BacFlashVer,Latest_webUIVersion,Latest_webUITypeCarrVer,Latest_webTypeDataVerNumber,Latest_operatorsVersion,Latest_phonePADPartitionedVersions,Latest_operatorId,gamePointId,gamePointDescription
#drop table if exists TCarbonSource
#drop table if exists TCarbon
#create table TCarbonSource (imei string,deviceInformationId int,MAC string,deviceColor string,device_backColor string,modelId string,marketName string,AMSize string,ROMSize string,CUPAudit string,CPIClocked string,series string,productionDate timestamp,bomCode string,internalModels string, deliveryTime string, channelsId string, channelsName string , deliveryAreaId string, deliveryCountry string, deliveryProvince string, deliveryCity string,deliveryDistrict string, deliveryStreet string, oxSingleNumber string, ActiveCheckTime string, ActiveAreaId string, ActiveCountry string, ActiveProvince string, Activecity string, ActiveDistrict string, ActiveStreet string, ActiveOperatorId string, Active_releaseId string, Active_EMUIVersion string, Active_operaSysVersion string, Active_BacVerNumber string, Active_BacFlashVer string, Active_webUIVersion string, Active_webUITypeCarrVer string,Active_webTypeDataVerNumber string, Active_operatorsVersion string, Active_phonePADPartitionedVersions string, Latest_YEAR int, Latest_MONTH int, Latest_DAY Decimal(30,10), Latest_HOUR string, Latest_areaId string, Latest_country string, Latest_province string, Latest_city string, Latest_district string, Latest_street string, Latest_releaseId string, Latest_EMUIVersion string, Latest_operaSysVersion string, Latest_BacVerNumber string, Latest_BacFlashVer string, Latest_webUIVersion string, Latest_webUITypeCarrVer string, Latest_webTypeDataVerNumber string, Latest_operatorsVersion string, Latest_phonePADPartitionedVersions string, Latest_operatorId string, gamePointDescription string,gamePointId double,contractNumber BigInt) STORED BY 'org.apache.carbondata.format'
#LOAD DATA INPATH 'D:\github\incubator-carbondata\integration\spark\src\test\resources\100_olap.csv' INTO table TCarbonSource options ('DELIMITER'=',', 'QUOTECHAR'='\', 'FILEHEADER'='imei,deviceInformationId,MAC,deviceColor,device_backColor,modelId,marketName,AMSize,ROMSize,CUPAudit,CPIClocked,series,productionDate,bomCode,internalModels,deliveryTime,channelsId,channelsName,deliveryAreaId,deliveryCountry,deliveryProvince,deliveryCity,deliveryDistrict,deliveryStreet,oxSingleNumber,ActiveCheckTime,ActiveAreaId,ActiveCountry,ActiveProvince,Activecity,ActiveDistrict,ActiveStreet,ActiveOperatorId,Active_releaseId,Active_EMUIVersion,Active_operaSysVersion,Active_BacVerNumber,Active_BacFlashVer,Active_webUIVersion,Active_webUITypeCarrVer,Active_webTypeDataVerNumber,Active_operatorsVersion,Active_phonePADPartitionedVersions,Latest_YEAR,Latest_MONTH,Latest_DAY,Latest_HOUR,Latest_areaId,Latest_country,Latest_province,Latest_city,Latest_district,Latest_street,Latest_releaseId,Latest_EMUIVersion,Latest_operaSysVersion,Latest_BacVerNumber,Latest_BacFlashVer,Latest_webUIVersion,Latest_webUITypeCarrVer,Latest_webTypeDataVerNumber,Latest_operatorsVersion,Latest_phonePADPartitionedVersions,Latest_operatorId,gamePointDescription,gamePointId,contractNumber')
#create table TCarbon (imei string,deviceInformationId int,MAC string,deviceColor string,device_backColor string,modelId string,marketName string,AMSize string,ROMSize string,CUPAudit string,CPIClocked string,series string,productionDate timestamp,bomCode string,internalModels string, deliveryTime string, channelsId string, channelsName string , deliveryAreaId string, deliveryCountry string, deliveryProvince string, deliveryCity string,deliveryDistrict string, deliveryStreet string, oxSingleNumber string, ActiveCheckTime string, ActiveAreaId string, ActiveCountry string, ActiveProvince string, Activecity string, ActiveDistrict string, ActiveStreet string, ActiveOperatorId string, Active_releaseId string, Active_EMUIVersion string, Active_operaSysVersion string, Active_BacVerNumber string, Active_BacFlashVer string, Active_webUIVersion string, Active_webUITypeCarrVer string,Active_webTypeDataVerNumber string, Active_operatorsVersion string, Active_phonePADPartitionedVersions string, Latest_YEAR int, Latest_MONTH int, Latest_DAY Decimal(30,10), Latest_HOUR string, Latest_areaId string, Latest_country string, Latest_province string, Latest_city string, Latest_district string, Latest_street string, Latest_releaseId string, Latest_EMUIVersion string, Latest_operaSysVersion string, Latest_BacVerNumber string, Latest_BacFlashVer string, Latest_webUIVersion string, Latest_webUITypeCarrVer string, Latest_webTypeDataVerNumber string, Latest_operatorsVersion string, Latest_phonePADPartitionedVersions string, Latest_operatorId string, gamePointDescription string,gamePointId double,contractNumber BigInt) STORED BY 'org.apache.carbondata.format'
#select * from TCarbonSource
#insert into TCarbon select * from TCarbonSource
#drop table if exists carbontable
#create table carbontable(test1 int, test2 array<String>,test3 array<bigint>,test4 array<int>,test5 array<decimal>,test6 array<timestamp>,test7 array<double>) STORED BY 'org.apache.carbondata.format'
alter table carbontable compact 'minor'
#drop table if exists bigi
#create table bigi(name string,salary bigint) stored by 'carbondata'
#load data inpath 'D:\github\FeatureTest\input\bigi.csv' into table bigi options('fileheader'='name,salary')
#drop table if exists bigd
#create table bigd(name string,salary decimal(10,5)) stored by 'carbondata'
#load data inpath 'D:\github\FeatureTest\input\bigd.csv' into table bigd options('fileheader'='name,salary')
#select * from bigd
#select * from bigi
#drop table if exists carbonTable
#CREATE TABLE carbonTable (ID Int, date Timestamp, country String, name String, phonetype String, serialname String, salary Decimal(17,2))STORED BY 'org.apache.carbondata.format'
#LOAD DATA LOCAL INPATH 'D:\github\incubator-carbondata\integration\spark\src\test\resources\decimalDataWithHeader.csv' into table carbonTable
#select salary from carbonTable order by salary
#select * from carbonTable
#CREATE TABLE filtertestTablesWithDecimal (ID decimal, date Timestamp, country String, name String, phonetype String, serialname String, salary int) STORED BY 'org.apache.carbondata.format'
#LOAD DATA LOCAL INPATH 'D:\github\incubator-carbondata\integration\spark\src\test\resources\dataDiff.csv' INTO TABLE filtertestTablesWithDecimal
#select id from filtertestTablesWithDecimal where id >999
#drop table if exists dict
#create table dict(name string) stored by 'carbondata'
#load data inpath 'D:\github\FeatureTest\input\dict\1.csv' into table dict options('fileheader'='name')
#load data inpath 'D:\github\FeatureTest\input\dict\2.csv' into table dict options('fileheader'='name')
#load data inpath 'D:\github\FeatureTest\input\dict\3.csv' into table dict options('fileheader'='name')
#select * from dict where name='ashok'
explain extended select * from dict where name='hello' order by name limit 2
#CREATE TABLE complexcarbontimestamptable (empno string,workdate Timestamp,punchinout array<Timestamp>, worktime struct<begintime:Timestamp, endtime:Timestamp>, salary double) STORED BY 'org.apache.carbondata.format'
#LOAD DATA local inpath 'D:\github\incubator-carbondata\integration\spark\src\test\resources\datasamplecomplex.csv' INTO TABLE complexcarbontimestamptable OPTIONS('DELIMITER'= ',', 'QUOTECHAR'= '"', 'FILEHEADER'='empno,workdate,punchinout,worktime,salary')
#select * from complexcarbontimestamptable
#drop table if exists  cardinalityTest
#CREATE TABLE IF NOT EXISTS cardinalityTest (country String, ID String, date Timestamp, name String,phonetype String, serialname String, salary Int) STORED BY 'org.apache.carbondata.format'
#LOAD DATA LOCAL INPATH 'D:\github\incubator-carbondata\integration\spark\src\test\resources\compaction/compaction1.csv' INTO TABLE cardinalityTest OPTIONS('DELIMITER'= ',', 'QUOTECHAR'= '"')
#LOAD DATA LOCAL INPATH 'D:\github\incubator-carbondata\integration\spark\src\test\resources\compaction/compactioncard2.csv' INTO TABLE cardinalityTest OPTIONS('DELIMITER'= ',', 'QUOTECHAR'= '"')
#LOAD DATA LOCAL INPATH 'D:\github\incubator-carbondata\integration\spark\src\test\resources\compaction/compaction3.csv' INTO TABLE cardinalityTest OPTIONS('DELIMITER'= ',', 'QUOTECHAR'= '"')
#alter table cardinalityTest compact 'major'
#show segments for table cardinalityTest
#select country,count(*) from cardinalityTest group by country
#drop table if exists DataRetentionTable
#CREATE table DataRetentionTable (ID int, date String, country String, name String,phonetype String, serialname String, salary int) stored by 'org.apache.carbondata.format'
#LOAD DATA LOCAL INPATH 'D:\github\incubator-carbondata\integration\spark\src\test\resources\dataretention1.csv' INTO TABLE DataRetentionTable OPTIONS('DELIMITER' =  ',')
#LOAD DATA LOCAL INPATH 'D:\github\incubator-carbondata\integration\spark\src\test\resources\dataretention2.csv' INTO TABLE DataRetentionTable OPTIONS('DELIMITER' =  ',')
#DELETE SEGMENT 1 FROM TABLE DataRetentionTable
#LOAD DATA LOCAL INPATH 'D:\github\incubator-carbondata\integration\spark\src\test\resources\dataretention1.csv' INTO TABLE DataRetentionTable OPTIONS('DELIMITER' =  ',')
#SELECT country, count(salary) AS amount FROM DataRetentionTable WHERE country IN ('china','ind','aus','eng') GROUP BY country
#clean files for table DataRetentionTable
#show segments for table DataRetentionTable
#DELETE SEGMENT 0 FROM TABLE DataRetentionTable
#DELETE SEGMENT 2 FROM TABLE DataRetentionTable
#DELETE SEGMENTS FROM TABLE DataRetentionTable where STARTTIME before '" + actualValue + "
#LOAD DATA LOCAL INPATH 'D:\github\incubator-carbondata\integration\spark\src\test\resources\dataretention3.csv' INTO TABLE DataRetentionTable OPTIONS('DELIMITER' =  ',')
#SELECT country, count(salary) AS amount FROM DataRetentionTable WHERE country IN ('china','ind','aus','eng') GROUP BY country
#drop table if exists THive
#create table THive (imei string,deviceInformationId int,MAC string,deviceColor string,device_backColor string,modelId string,marketName string,AMSize string,ROMSize string,CUPAudit string,CPIClocked string,series string,productionDate timestamp,bomCode string,internalModels string, deliveryTime string, channelsId string, channelsName string , deliveryAreaId string, deliveryCountry string, deliveryProvince string, deliveryCity string,deliveryDistrict string, deliveryStreet string, oxSingleNumber string, ActiveCheckTime string, ActiveAreaId string, ActiveCountry string, ActiveProvince string, Activecity string, ActiveDistrict string, ActiveStreet string, ActiveOperatorId string, Active_releaseId string, Active_EMUIVersion string, Active_operaSysVersion string, Active_BacVerNumber string, Active_BacFlashVer string, Active_webUIVersion string, Active_webUITypeCarrVer string,Active_webTypeDataVerNumber string, Active_operatorsVersion string, Active_phonePADPartitionedVersions string, Latest_YEAR int, Latest_MONTH int, Latest_DAY Decimal(30,10), Latest_HOUR string, Latest_areaId string, Latest_country string, Latest_province string, Latest_city string, Latest_district string, Latest_street string, Latest_releaseId string, Latest_EMUIVersion string, Latest_operaSysVersion string, Latest_BacVerNumber string, Latest_BacFlashVer string, Latest_webUIVersion string, Latest_webUITypeCarrVer string, Latest_webTypeDataVerNumber string, Latest_operatorsVersion string, Latest_phonePADPartitionedVersions string, Latest_operatorId string, gamePointDescription string,gamePointId double,contractNumber BigInt) ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
#LOAD DATA local INPATH 'D:\github\incubator-carbondata\integration\spark/src/test/resources/100_olap.csv' INTO TABLE THive
#drop table if exists TCarbon
#create table TCarbon (MAC string,deviceInformationIdSum int) STORED BY 'org.apache.carbondata.format'
#select MAC,sum(deviceInformationId+ 10) as a from THive group by MAC
#load data inpath 'D:\github\FeatureTest\input\ins.csv' into table TCarbon options('fileheader'='MAC,deviceInformationIdSum')
#insert into TCarbon select MAC,sum(deviceInformationId+ 10) as a from THive group by MAC
#drop table if exists dict
#create table dict(name string, mobile string) stored by 'carbondata'
#load data inpath 'D:\github\FeatureTest\input\dict\1.csv' into table dict options('fileheader'='name,mobile')
explain extended select name,mobile from dict where name='hello' order by name limit 2
#drop table if exists Carbon_automation_test
#drop table if exists Carbon_automation_test_hive
#create table if not exists Carbon_automation_test (imei string,deviceInformationId int,MAC string,deviceColor string,device_backColor string,modelId string,marketName string,AMSize string,ROMSize string,CUPAudit string,CPIClocked string,series string,productionDate timestamp,bomCode string,internalModels string, deliveryTime string, channelsId string, channelsName string , deliveryAreaId string, deliveryCountry string, deliveryProvince string, deliveryCity string,deliveryDistrict string, deliveryStreet string, oxSingleNumber string,contractNumber int, ActiveCheckTime string, ActiveAreaId string, ActiveCountry string, ActiveProvince string, Activecity string, ActiveDistrict string, ActiveStreet string, ActiveOperatorId string, Active_releaseId string, Active_EMUIVersion string, Active_operaSysVersion string, Active_BacVerNumber string, Active_BacFlashVer string, Active_webUIVersion string, Active_webUITypeCarrVer string,Active_webTypeDataVerNumber string, Active_operatorsVersion string, Active_phonePADPartitionedVersions string, Latest_YEAR int, Latest_MONTH int, Latest_DAY int, Latest_HOUR string, Latest_areaId string, Latest_country string, Latest_province string, Latest_city string, Latest_district string, Latest_street string, Latest_releaseId string, Latest_EMUIVersion string, Latest_operaSysVersion string, Latest_BacVerNumber string, Latest_BacFlashVer string, Latest_webUIVersion string, Latest_webUITypeCarrVer string, Latest_webTypeDataVerNumber string, Latest_operatorsVersion string, Latest_phonePADPartitionedVersions string, Latest_operatorId string, gamePointId int,gamePointDescription string)  USING org.apache.spark.sql.CarbonSource OPTIONS('dbName'='default', 'tableName'='Carbon_automation_test','DICTIONARY_INCLUDE'='Latest_MONTH,Latest_DAY,deviceInformationId')    
#create table if not exists Carbon_automation_test_hive (imei string,deviceInformationId int,MAC string,deviceColor string,device_backColor string,modelId string,marketName string,AMSize string,ROMSize string,CUPAudit string,CPIClocked string,series string,productionDate timestamp,bomCode string,internalModels string, deliveryTime string, channelsId string, channelsName string , deliveryAreaId string, deliveryCountry string, deliveryProvince string, deliveryCity string,deliveryDistrict string, deliveryStreet string, oxSingleNumber string,contractNumber int, ActiveCheckTime string, ActiveAreaId string, ActiveCountry string, ActiveProvince string, Activecity string, ActiveDistrict string, ActiveStreet string, ActiveOperatorId string, Active_releaseId string, Active_EMUIVersion string, Active_operaSysVersion string, Active_BacVerNumber string, Active_BacFlashVer string, Active_webUIVersion string, Active_webUITypeCarrVer string,Active_webTypeDataVerNumber string, Active_operatorsVersion string, Active_phonePADPartitionedVersions string, Latest_YEAR int, Latest_MONTH int, Latest_DAY int, Latest_HOUR string, Latest_areaId string, Latest_country string, Latest_province string, Latest_city string, Latest_district string, Latest_street string, Latest_releaseId string, Latest_EMUIVersion string, Latest_operaSysVersion string, Latest_BacVerNumber string, Latest_BacFlashVer string, Latest_webUIVersion string, Latest_webUITypeCarrVer string, Latest_webTypeDataVerNumber string, Latest_operatorsVersion string, Latest_phonePADPartitionedVersions string, Latest_operatorId string, gamePointId int,gamePointDescription string)row format delimited fields terminated by ','
#LOAD DATA LOCAL INPATH 'D:/github/incubator-carbondata/integration/spark/src/test/resources/100_olap.csv' INTO table Carbon_automation_test_hive
#INSERT INTO table Carbon_automation_test select * from Carbon_automation_test_hive
#select imei,series from Carbon_automation_test where series='7Series' order by imei
#select imei,series from Carbon_automation_test where series='7Series' order by imei limit 1
#explain extended select imei,series from Carbon_automation_test_hive where series='7Series' order by imei limit 10