#drop table if exists temp_25
#create table temp_25(dimension1 String,dimension2 String,dimension3 String,dimension4 String,dimension5 String,dimension6 String,dimension7 int,dimension8 String,dimension9 String,dimension10 String,dimension11 String,dimension12 String,dimension13 String,dimension14 int,dimension15 String,dimension16 String,dimension17 String,dimension18 String,dimension19 String,dimension20 String,dimension21 int,dimension22 String,dimension23 long,dimension24 String,dimension25 String,dimension26 String,dimension27 String,dimension28 int,dimension29 String,dimension30 String,dimension31 String,dimension32 String,dimension33 String,dimension34 String,dimension35 int,dimension36 String,dimension37 String,dimension38 String,dimension39 String,dimension40 String,dimension41 String,dimension42 int,dimension43 String,dimension44 String,dimension45 String,dimension46 long,dimension47 String,dimension48 String,dimension49 int,dimension50 String,dimension51 String,dimension52 String,dimension53 String,dimension54 String,dimension55 String,dimension56 int,dimension57 String,dimension58 String,dimension59 String,dimension60 String,dimension61 String,dimension62 String,dimension63 int,dimension64 String,dimension65 String,dimension66 String,dimension67 String,dimension68 String,dimension69 long,dimension70 int,dimension71 String,dimension72 String,dimension73 String,dimension74 String,dimension75 String,dimension76 String,dimension77 int,dimension78 String,dimension79 String,dimension80 String,dimension81 String,dimension82 String,dimension83 String,dimension84 int,dimension85 String,dimension86 String,dimension87 String,dimension88 String,dimension89 String,dimension90 String,dimension91 int,dimension92 long,dimension93 String,dimension94 String,dimension95 String,dimension96 String,dimension97 String,dimension98 int,dimension99 String,dimension100 String)ROW format delimited FIELDS terminated by ','
#LOAD DATA LOCAL INPATH '/Users/ashok.kumar/github/workspace/spark/input/orc/100/20190425/' INTO table temp_25
#
#set hive.exec.dynamic.partition.mode=nonstrict
#
#drop table if exists device_orc_using_25
#create table device_orc_using_25(dimension1 String,dimension2 String,dimension3 String,dimension4 String,dimension5 String,dimension6 String,dimension7 int,dimension8 String,dimension9 String,dimension10 String,dimension11 String,dimension12 String,dimension13 String,dimension14 int,dimension15 String,dimension16 String,dimension17 String,dimension18 String,dimension19 String,dimension20 String,dimension21 int,dimension22 String,dimension23 long,dimension24 String,dimension25 String,dimension26 String,dimension27 String,dimension28 int,dimension29 String,dimension30 String,dimension31 String,dimension32 String,dimension33 String,dimension34 String,dimension35 int,dimension36 String,dimension37 String,dimension38 String,dimension39 String,dimension40 String,dimension41 String,dimension42 int,dimension43 String,dimension44 String,dimension45 String,dimension46 long,dimension47 String,dimension48 String,dimension49 int,dimension50 String,dimension51 String,dimension52 String,dimension53 String,dimension54 String,dimension55 String,dimension56 int,dimension57 String,dimension58 String,dimension59 String,dimension60 String,dimension61 String,dimension62 String,dimension63 int,dimension64 String,dimension65 String,dimension66 String,dimension67 String,dimension68 String,dimension69 long,dimension70 int,dimension71 String,dimension72 String,dimension73 String,dimension74 String,dimension75 String,dimension76 String,dimension77 int,dimension78 String,dimension79 String,dimension80 String,dimension81 String,dimension82 String,dimension83 String,dimension84 int,dimension85 String,dimension86 String,dimension87 String,dimension88 String,dimension89 String,dimension90 String,dimension91 int,dimension92 long,dimension93 String,dimension94 String,dimension95 String,dimension96 String,dimension97 String,dimension98 int,dimension99 String,dimension100 String) USING orc PARTITIONED BY(dimension100)
#
#select * from temp_25 limit 2
#insert into device_orc_using_25 select * from temp_25
set spark.sql.orc.impl=native
#set spark.sql.orc.enableVectorizedReader=false
select count(*) from (select dimension1,dimension2,dimension3,dimension4,dimension100 from device_orc_using_2)
#select * from temp_25 limit 5
